USE example;
DROP TABLE REGISTROS;
DROP TABLE ORDENDISENIO;
CREATE TABLE ORDENDISENIO(
    ID INT UNIQUE AUTO_INCREMENT NOT NULL,
    RESPONSABLE_CEDULA CHAR(10) NOT NULL,
    PRODUCTO VARCHAR(100) PRIMARY KEY UNIQUE,
    MARCA CHAR(30) NOT NULL,
    FECHAENTREGA DATETIME NOT NULL,
    ESTADO INT NOT NULL, -- 1=APROBADA  2=EN DISENIO  3= DESAPROBADA  4= REVISANDO
    Foreign Key (RESPONSABLE_CEDULA) REFERENCES PERSONAS(CEDULA)
);

CREATE TABLE REGISTROS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PRODUCTO VARCHAR(100) NOT NULL,
    DISENIADOR CHAR(10) NOT NULL,
    HORA_INICIO DATETIME NOT NULL,
    HORA_FINAL DATETIME,
    OBSERVACIONES VARCHAR(255),
    Foreign Key (PRODUCTO) REFERENCES ORDENDISENIO(PRODUCTO)
);
